# Generated by Django 5.2.2 on 2025-07-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_admin', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=150, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('contraseña', models.CharField(max_length=255)),
                ('es_principal', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'administrador',
            },
        ),
    ]
