# Generated by Django 5.2.2 on 2025-07-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='contraseña',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
