# Generated by Django 5.2.2 on 2025-07-01 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresosEgresos',
            fields=[
                ('id_transaccion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('Ingreso', 'Ingreso'), ('Egreso', 'Egreso')], max_length=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_admin', models.ForeignKey(db_column='id_admin', on_delete=django.db.models.deletion.CASCADE, to='administracion.administrador')),
            ],
            options={
                'db_table': 'ingresos_egresos',
            },
        ),
    ]
