# Generated by Django 5.2.2 on 2025-07-19 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_alter_administrador_contraseña'),
        ('ingresos_egresos', '0001_initial'),
        ('inventarios', '0002_remove_inventario_id_tipo_inventario_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('id_admin', models.ForeignKey(db_column='id_admin', on_delete=django.db.models.deletion.CASCADE, to='administracion.administrador')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, to='inventarios.inventario')),
            ],
            options={
                'db_table': 'ventas',
            },
        ),
    ]
