# Generated by Django 5.2.2 on 2025-07-19 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos_egresos', '0002_ventas'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
