# Generated by Django 5.2.2 on 2025-08-05 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos_egresos', '0003_ventas_descripcion'),
        ('inventarios', '0002_remove_inventario_id_tipo_inventario_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='id_producto',
            field=models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventarios.inventario'),
        ),
    ]
