# Generated by Django 5.2.2 on 2025-08-05 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos_egresos', '0004_alter_ventas_id_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='nombre_producto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ventas',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
