# Generated by Django 5.2.2 on 2025-08-05 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos_egresos', '0005_ventas_nombre_producto_ventas_precio_unitario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='descripcion',
        ),
    ]
