# Generated by Django 5.2.2 on 2025-08-05 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos_egresos', '0006_remove_ventas_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='contenido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ventas',
            name='unidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
