# Generated by Django 5.2.2 on 2025-08-05 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos_egresos', '0007_ventas_contenido_ventas_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
