# Generated by Django 5.2.2 on 2025-08-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos_egresos', '0008_ventas_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='anulada',
            field=models.BooleanField(default=False),
        ),
    ]
