# Generated by Django 5.2.2 on 2025-08-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos_egresos', '0009_ventas_anulada'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresosegresos',
            name='anulada',
            field=models.BooleanField(default=False),
        ),
    ]
