# Generated by Django 5.2.2 on 2025-07-01 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id_lote', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('hectareas', models.FloatField()),
                ('tipo_arbusto', models.CharField(choices=[('Café', 'Café'), ('Cardamomo', 'Cardamomo')], max_length=20)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
            ],
            options={
                'db_table': 'lote',
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('tipo_pago', models.CharField(choices=[('Horas', 'Horas'), ('Kilos', 'Kilos')], max_length=10, primary_key=True, serialize=False)),
                ('valor', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'pagos',
            },
        ),
        migrations.CreateModel(
            name='Recoleccion',
            fields=[
                ('id_recoleccion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_producto', models.CharField(choices=[('Café', 'Café'), ('Cardamomo', 'Cardamomo')], max_length=20)),
                ('kilos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('horas_trabajadas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('id_empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, to='personal.empleado')),
                ('id_lote', models.ForeignKey(db_column='id_lote', on_delete=django.db.models.deletion.CASCADE, to='cafe_cardamomo.lote')),
                ('tipo_pago', models.ForeignKey(db_column='tipo_pago', on_delete=django.db.models.deletion.CASCADE, to='cafe_cardamomo.pagos')),
            ],
            options={
                'db_table': 'recoleccion',
            },
        ),
    ]
