# Generated by Django 5.2.2 on 2025-07-14 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_cardamomo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recoleccion',
            name='valor_pago',
        ),
    ]
