# Generated by Django 5.2.2 on 2025-08-07 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_cardamomo', '0002_remove_recoleccion_valor_pago'),
        ('personal', '0002_remove_empleado_id_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoleccion',
            name='nombre_empleado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recoleccion',
            name='nombre_lote',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recoleccion',
            name='id_empleado',
            field=models.ForeignKey(blank=True, db_column='id_empleado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.empleado'),
        ),
        migrations.AlterField(
            model_name='recoleccion',
            name='id_lote',
            field=models.ForeignKey(blank=True, db_column='id_lote', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cafe_cardamomo.lote'),
        ),
    ]
