# Generated by Django 5.2.4 on 2025-08-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_cardamomo', '0002_remove_recoleccion_valor_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='cantidad_actual',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lote',
            name='cantidad_maxima',
            field=models.IntegerField(default=0),
        ),
    ]
