# Generated by Django 5.2.2 on 2025-08-14 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_cardamomo', '0003_recoleccion_nombre_empleado_recoleccion_nombre_lote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoleccion',
            name='valor_pago',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
