# Generated by Django 5.2.2 on 2025-08-20 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_cardamomo', '0003_lote_cantidad_actual_lote_cantidad_maxima'),
        ('cafe_cardamomo', '0004_recoleccion_valor_pago'),
    ]

    operations = [
    ]
