# Generated by Django 5.2.2 on 2025-07-01 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cafe_cardamomo', '0001_initial'),
        ('inventarios', '0001_initial'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id_proceso', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('Producción', 'Producción'), ('Agrícola', 'Agrícola')], max_length=20)),
                ('tipo_producto', models.CharField(blank=True, choices=[('Café', 'Café'), ('Cardamomo', 'Cardamomo')], max_length=20, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('cantidad_agroquimico', models.CharField(blank=True, max_length=100, null=True)),
                ('id_empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, to='personal.empleado')),
                ('id_inventario', models.ForeignKey(blank=True, db_column='id_inventario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventarios.inventario')),
                ('id_lote', models.ForeignKey(blank=True, db_column='id_lote', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cafe_cardamomo.lote')),
            ],
            options={
                'db_table': 'proceso',
            },
        ),
    ]
