# Generated by Django 5.2.2 on 2025-07-09 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proceso',
            name='cantidad_agroquimico',
        ),
    ]
