# Generated by Django 5.2.2 on 2025-08-07 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_remove_empleado_id_admin'),
        ('procesos', '0002_remove_proceso_cantidad_agroquimico'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='nombre_agroquimico',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proceso',
            name='nombre_empleado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proceso',
            name='nombre_lote',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='id_empleado',
            field=models.ForeignKey(blank=True, db_column='id_empleado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.empleado'),
        ),
    ]
