# Generated by Django 5.2.2 on 2025-08-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0003_proceso_nombre_agroquimico_proceso_nombre_empleado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='nombre_agroquimico',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
