# Generated by Django 5.2.2 on 2025-07-01 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_empleado', models.CharField(choices=[('Vinculado', 'Vinculado'), ('No vinculado', 'No vinculado')], max_length=15)),
                ('pago_contrato', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id_admin', models.ForeignKey(db_column='id_admin', on_delete=django.db.models.deletion.CASCADE, to='administracion.administrador')),
            ],
            options={
                'db_table': 'empleado',
            },
        ),
    ]
