# Generated by Django 5.2.2 on 2025-07-09 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='id_admin',
        ),
    ]
