# Generated by Django 5.2.2 on 2025-07-01 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cafe_cardamomo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoInventario',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_inventario',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('stock', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unidad', models.CharField(blank=True, max_length=50, null=True)),
                ('categoria', models.CharField(blank=True, choices=[('Herramienta', 'Herramienta'), ('Maquina', 'Maquina')], max_length=20, null=True)),
                ('estado', models.CharField(blank=True, choices=[('Buena', 'Buena'), ('Regular', 'Regular'), ('Mala', 'Mala')], max_length=10, null=True)),
                ('tipo_arbusto', models.CharField(blank=True, choices=[('Café', 'Café'), ('Cardamomo', 'Cardamomo')], max_length=20, null=True)),
                ('fecha_siembra', models.DateField(blank=True, null=True)),
                ('renovacion', models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], max_length=2, null=True)),
                ('contenido', models.CharField(blank=True, max_length=100, null=True)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id_lote', models.ForeignKey(blank=True, db_column='id_lote', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cafe_cardamomo.lote')),
                ('id_tipo', models.ForeignKey(db_column='id_tipo', on_delete=django.db.models.deletion.CASCADE, to='inventarios.tipoinventario')),
            ],
            options={
                'db_table': 'inventario',
            },
        ),
    ]
