# Generated by Django 5.2.2 on 2025-08-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0002_remove_inventario_id_tipo_inventario_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='nombre_lote',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
