# Generated by Django 5.2.4 on 2025-08-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0002_remove_inventario_id_tipo_inventario_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='tala',
            field=models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], max_length=2, null=True),
        ),
    ]
