# Generated by Django 5.2.2 on 2025-08-20 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0003_inventario_nombre_lote'),
        ('inventarios', '0003_inventario_tala'),
    ]

    operations = [
    ]
